### ISSUE TITLE
Whats the purpose of angular-linq

### ISSUE THREAD

**Issue by bastienJS** [Angular-Public/angular-linq#1]
I was browsing for a linq.js bower package and stumbled over here...

Then I asked myself and YOU of course what is the advantage of wrapping linq.js with angular to do something like:

$linq.Enumerable()

without angular-linq I just do:

Enumerable.from

I just do not get it...

**Comment by angularPublic** [comment]
yes you can do Enumerable.from in a plain javascript way.
$linq.Enumerable() can be injected where ever it is needed without polluting global namespace using angular way. Other than that it does the same that linq.js does.

Also, I did not had an option to include linq.js using bower for my angular application.

**Comment by bastienJS** [comment]
its just bower install linqjs, that worked for me and it has the latest beta5 :-)
