### ISSUE TITLE
#5 module registration not working with angular 1.4.5

### ISSUE THREAD

**Issue by ecsplendid** [Angular-Public/angular-linq#6]
Hi :)

This code change doesn't seem to be coming down on Bower?

Pro tip for others with this issue. You can fix it in the build script.

``` javascript
.pipe(replace(`.module('angular-linq')`, `.module('angular-linq',[])`))
```

Best

Tim

**Comment by angularPublic** [comment]
Thanks for the info.
Latest changes pushed to repository master. And updated bower's pull tag to latest v1.0.1

You may need to pump your your version for angular-linq in your bower.json, if it still uses v1.0.0.

Have a great day.
