### ISSUE TITLE
Except and Intersect behave strange.

### ISSUE THREAD

**Issue by vinnichase** [Angular-Public/angular-linq#7]
I have two arrays of objects with the same structure. every object has a property 'selected' (eg.`{selected:true, ...}`). i want to extract the elements with different `selected`values. so 

`$linq.Enumerable().From(seq1).Except(seq2, "$.selected")`

should return all elements with different `selected` values right? But this works only with `selected = true` of seq1 objects. I think its matching each object so i have to provide another compare-property to match the `selected` value of the same objects. something like:

`function (a,b) { (return a.id == b.id) && (a.selected == b.selected) }`

for the moment this works for me (dont know why) cause i just need to match the true-values: 

`From(seq1).Except(seq2, '$.id && $.selected')`

But i think it may help for the future.

**Comment by angularPublic** [comment]
Thanks for the info.
