### ISSUE TITLE
Angular2 linq to firebase

### ISSUE THREAD

**Issue by davidrensh** [Angular-Public/angular-linq#8]
Hi, your contribution is awesome.
Is it possible to create Angular2 linq to firebase?

**Comment by angularPublic** [comment]
David,
I just have created ng2-linq module.  But just a place holder for the name. I will update the content as soon as I can.

**Comment by davidrensh** [comment]
That would be great. This is so important for those developers from .net stack developers. I asked question to David East /#askFirebase about possibility for integrate graphQL into angularFire2 or just extent agularFire api. And, I also asked about angularFire road map because the angularFire API is not enough at all. 
I know it will be tough job to create Angular2 linq to firebase. Please let us know if we can give a hand.

It could replace angularFire if it's going well. :-)
